In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import scale
import matplotlib.pylab as plt

In [2]:
olddf=pd.read_json('../01_Preprocessing//First.json').sort_index()

In [3]:
olddf.head(2)

,country,countryCoded,degree,degreeCoded,eng,engCoded,fieldGroup,fund,gpaBachelors,gpaMasters,gre,highLevelBachUni,highLevelMasterUni,paper,targetUni,uniAccepted,uniBachelors,uniMasters,uniSelected,year
2,united kingdom,4,Doctorate,1,High,1,7,True,3.5,3.442986,False,False,False,6.0,heriot-watt,n/a,azad,n/a,heriot-watt,2007
3,united states,0,Doctorate,1,VeryHigh,0,5,True,2.5,3.500000,True,True,False,10.5,northwestern,switzerland,mashhad,portland state,northwestern,2010

In [4]:
olddf.targetUni.replace('n/a',np.nan,inplace=True)

In [5]:
olddf.columns

Index([u'country', u'countryCoded', u'degree', u'degreeCoded', u'eng',
       u'engCoded', u'fieldGroup', u'fund', u'gpaBachelors', u'gpaMasters',
       u'gre', u'highLevelBachUni', u'highLevelMasterUni', u'paper',
       u'targetUni', u'uniAccepted', u'uniBachelors', u'uniMasters',
       u'uniSelected', u'year'],
      dtype='object')

In [6]:
df=olddf[['countryCoded', 'degreeCoded','engCoded', 'fieldGroup', 'fund',
          'gpaBachelors', 'gpaMasters','gre', 'highLevelBachUni', 'highLevelMasterUni','paper','year']]

In [7]:
met=['pearson', 'kendall', 'spearman']
df.corr(method=met[0])

,countryCoded,degreeCoded,engCoded,fieldGroup,fund,gpaBachelors,gpaMasters,gre,highLevelBachUni,highLevelMasterUni,paper,year
countryCoded,1.000000,-0.233423,0.198801,-0.072802,-0.214348,-0.071829,-0.003735,-0.344367,-0.141624,-0.184028,-0.059172,0.045596
degreeCoded,-0.233423,1.000000,-0.180362,0.050019,0.507069,0.055572,0.034925,0.277032,0.145979,0.530627,0.366760,0.067163
engCoded,0.198801,-0.180362,1.000000,-0.024266,-0.240378,-0.150995,-0.062658,-0.280492,-0.246722,-0.158683,-0.020208,-0.039441
fieldGroup,-0.072802,0.050019,-0.024266,1.000000,0.029535,0.030246,0.059075,0.010689,0.020632,0.043751,0.025284,0.037319
fund,-0.214348,0.507069,-0.240378,0.029535,1.000000,0.154465,0.060127,0.300314,0.209722,0.350306,0.270571,0.071757
gpaBachelors,-0.071829,0.055572,-0.150995,0.030246,0.154465,1.000000,0.219793,0.023537,0.023148,0.034671,-0.020031,0.069588
gpaMasters,-0.003735,0.034925,-0.062658,0.059075,0.060127,0.219793,1.000000,-0.006572,0.027380,-0.001257,0.057022,0.064811
gre,-0.344367,0.277032,-0.280492,0.010689,0.300314,0.023537,-0.006572,1.000000,0.253372,0.217861,0.089604,0.006196
highLevelBachUni,-0.141624,0.145979,-0.246722,0.020632,0.209722,0.023148,0.027380,0.253372,1.000000,0.266335,-0.005919,-0.052365
highLevelMasterUni,-0.184028,0.530627,-0.158683,0.043751,0.350306,0.034671,-0.001257,0.217861,0.266335,1.000000,0.186581,-0.000902
paper,-0.059172,0.366760,-0.020208,0.025284,0.270571,-0.020031,0.057022,0.089604,-0.005919,0.186581,1.000000,0.034687
year,0.045596,0.067163,-0.039441,0.037319,0.071757,0.069588,0.064811,0.006196,-0.052365,-0.000902,0.034687,1.000000

In [8]:

# Canada, Masters, Medium Eng , Want Fund, 2.5GPA , 0GPA MS, NoGRE, NoTopUni,noTopUniMS, 1Paper, 2017
me=[1, 0, 2, 0, True, 2.5, 0, False, False, False, 1, 2017]
me=[4, 1, 1, 7, True, 3.5, 3.44299, False, False, False, 4, 2007]
sim=df.corrwith(Series(me), drop=True,axis=1).dropna()
sim

Series([], dtype: float64)